### ISSUE TITLE
[bug] Banners plugin inompatibility

### ISSUE THREAD

**Issue by oyes77** [ras0q/obsidian-graph-banner#17]
![image](https://github.com/ras0q/obsidian-graph-banner/assets/53545025/b66e2cc5-d8ab-47b4-bbcd-c337b13c9907)
![image](https://github.com/ras0q/obsidian-graph-banner/assets/53545025/6debca65-43f8-4393-b297-fe7b7f1517bb)
![image](https://github.com/ras0q/obsidian-graph-banner/assets/53545025/3f8609e3-7f17-458f-a932-27cd3ca6dfeb)
The graph banner does not appear unless I either disable the banners plugin, or disable the graph banners plugin and re-enable it, then it only works in the displaying note when I switched back on the plugin.

Banners plugin version is the last beta installed via BRAT, which is the functional one since some months ago.

**Comment by ras0q** [comment]
Do you mean that you want the banner to appear in a file that is already open when the plugin is activated?

At present, that feature has not been implemented (PR is welcome).

Please reopen the file after enabling this.
