### ISSUE TITLE
[Bug] Typo and style settings bug

### ISSUE THREAD

**Issue by oyes77** [ras0q/obsidian-graph-banner#18]
![image](https://github.com/ras0q/obsidian-graph-banner/assets/53545025/1c330380-96c9-49d3-beb5-4edd0563fc8a)
I think the plugin doesn't really disable it's styling when disabled, that's why the other bug I reported happens (really guessing here sinec i'm not a programmer)
that leads to a new instance of style settings or the snippet that allows the style settings integration each time you enable the plugin.

**Comment by oyes77** [comment]
also the "Braph" typo LOL

**Comment by ras0q** [comment]
Thank you for the bug report!
I've fixed the issue where the plugin instance wasn't destroyed upon disabling (and typos!).
Please try version 1.0.2.

Regarding the style settings, I couldn't find a way to disable this plugin's style settings within the Style Settings plugin documentation.
It seems to be an issue with the Style Settings plugin itself.
Please try reloading the app to disable style settings.
https://github.com/mgmeyers/obsidian-style-settings#plugin-support
