### ISSUE TITLE
[Feature Request] Blacklist notes from showing the banner

### ISSUE THREAD

**Issue by Ekb18** [ras0q/obsidian-graph-banner#22]
I really like the plug-in, however, it would be wonderful if we could blacklist certain notes from showing the local graph, such as notes pinned in the sidebars.

**Comment by ras0q** [comment]
Thank you for the feedback!
Unfortunately, this plugin cannot control the content of the local graph, so please try to use the "Filters".
![image](https://github.com/ras0q/obsidian-graph-banner/assets/66677201/980dedee-a009-4bb5-8bff-22502f1de8a2)

**Comment by Ekb18** [comment]
I actually meant that some notes will not show the banner when active, not whether or not they show up in the local graph.

**Comment by ras0q** [comment]
I'm sorry I misread it.
I've reopened the issue.

**Comment by madigan** [comment]
@ras0q What about a blacklist feature in settings that allows users to suppress the graph banner based on file name or a file property? If you'd be open to it I could put a PR together.

**Comment by ras0q** [comment]
@madigan very good!
Actually, I was thinking of adopting .gitignore syntax for blacklist implementation, using https://github.com/kaelzhang/node-ignore, etc. if you don't have a strong preference.
If you could put a PR, I would very much appreciate it!

**Comment by ras0q** [comment]
@madigan 
I couldn't quite imagine how to use properties to ignore files, but indeed, ignoring the meta notes seems like a good strategy. I really appreciate it if those who are motivated can work on it.

**Comment by Moyf** [comment]
With this new feature, is it possible to blacklist whole folder (`/DontShow/ThisFolder/` ), just like the gitignore syntax?
