### ISSUE TITLE
[bug] Plugin opens new window with graph

### ISSUE THREAD

**Issue by madigan** [ras0q/obsidian-graph-banner#36]
Given a vault (Obsidian 1.6.3) with the latest version of the plugin (1.0.3) which was working until recently
When I open a note
Then obsidian opens a new window with a graph view
Instead it should just display the note with the embedded graph.

I think the problem is the code that is opening a new graph leaf and trying to find the window with an ID of 1: (src/main.ts#30)

```typescript
const mainWindow = obsidianWindows.find((win) => win.id === 1);
```

I do not fully understand what this method is doing, but I do not think that any of the windows have an ID of 1. Would it make sense to get the lowest ID instead?

```typescript
const mainWindow = obsidianWindows
  .sort((a, b) => b.id - a.id)
  .first();
```

If you could explain the intent of this method I could try to put together a patch.

[edit]: Even with this change the graph window opens up (which is disruptive when obsidian is maximized on MacOS).

**Comment by ras0q** [comment]
@madigan I have fixed the use of id. Could you try v1.2.0 to see if it works correctly?
