### ISSUE TITLE
When i open Obsidian it open a graph note, close it then completly freez

### ISSUE THREAD

**Issue by Purintu** [ras0q/obsidian-graph-banner#44]
Here is a video that show it 
[f98814b2-3871-4ef9-b23d-d222efaa39ee.webm](https://github.com/ras0q/obsidian-graph-banner/assets/143506802/9508c431-2934-4945-9b5d-8eeb60d104fd)
(for the no longer plugin it's about another plugin that i doubt it was the cause of the problem)

**Comment by Aurala** [comment]
I had the same problem. Obsidian works OK after disabling the plugin.

**Comment by kkingsbe** [comment]
Also experiencing this

**Comment by ras0q** [comment]
@Purintu @kkingsbe @kkingsbe 
In v1.3.2, I changed the way to open the graph. Could you check to see if the issue has been fixed?

**Comment by Purintu** [comment]
@ras0q 
I installed the plugin and yeah it works good for me no crash when i start obsidian

**Comment by ras0q** [comment]
Thank you!
I don't know the exact cause, but I believe this issue has been resolved.
