### ISSUE TITLE
[Bug] ~ Conflict between plugins (Metadata Menu and MediaDB) and Individual Graph note would pop up in a new window

### ISSUE THREAD

**Issue by MojoMole** [ras0q/obsidian-graph-banner#48]
This is a video of the pop up into a new note issue: 

https://github.com/ras0q/obsidian-graph-banner/assets/174889845/07c62d54-c723-4348-b85d-97609dc87743

I have uninstalled and retested it doesn't have the problem with the other plugins are uninstalled, and this is a video of the Conflict graph banner has been having with Metadata Menu and MediaDB in my Vault. 

https://github.com/ras0q/obsidian-graph-banner/assets/174889845/c677428d-04c5-4a87-a2ee-56518275827e

**Comment by Moyf** [comment]
I encountered the same issue on my end.

However, I discovered that if I open the "Local Graph" window beforehand and then enable the plugin, the issue does not occur.
![image](https://github.com/user-attachments/assets/cf5443e1-60d9-464c-bf17-daf2bca13b9f)

Could it be related to the existence of the "Local Graph" window already?

**Comment by ras0q** [comment]
@MojoMole @Moyf  In v1.3.2, I changed the way to open the graph. Could you check to see if the issue has been fixed?

**Comment by Moyf** [comment]
> @MojoMole @Moyf In v1.3.2, I changed the way to open the graph. Could you check to see if the issue has been fixed?

It seems that it's working fine on my end!  😄

**Comment by MojoMole** [comment]
> @MojoMole @Moyf In v1.3.2, I changed the way to open the graph. Could you check to see if the issue has been fixed?

It's working normally on my side too

**Comment by ras0q** [comment]
Thanks! I'll close the issue...
